export const SKILL_TAXONOMY = [
  "react",
  "next.js",
  "javascript",
  "typescript",
  "node.js",
  "express",
  "nestjs",
  "python",
  "django",
  "flask",
  "java",
  "spring",
  "c#",
  ".net",
  "go",
  "rust",
  "php",
  "laravel",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "graphql",
  "rest api",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "gcp",
  "terraform",
  "linux",
  "git",
  "github actions",
  "ci/cd",
  "tailwind css",
  "html",
  "css",
  "sass",
  "redux",
  "zustand",
  "prisma",
  "supabase",
  "firebase",
  "cloudinary",
  "openai",
  "machine learning",
  "data analysis",
  "sql",
  "nosql",
  "microservices",
  "jest",
  "playwright",
  "cypress",
  "selenium",
  "figma",
  "webpack",
  "vite",
  "nlp",
  "llm",
  "prompt engineering",
  "agile",
  "scrum",
  "leadership",
  "communication"
];

export const SKILL_ALIASES = {
  reactjs: "react",
  "react.js": "react",
  nextjs: "next.js",
  node: "node.js",
  nodejs: "node.js",
  "express.js": "express",
  postgres: "postgresql",
  postgresql: "postgresql",
  js: "javascript",
  ts: "typescript",
  tailwind: "tailwind css",
  "restful api": "rest api",
  api: "rest api",
  ci: "ci/cd",
  cd: "ci/cd",
  github: "git",
  llms: "llm"
};
